mqtt:
  hostUrl: tcp://10.71.16.208:1883
  username: admin
  password: wanda@1234
  client-id: IOT-EPC-Pj3506811020-byq
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1
  sendtopic: project/gcId/report
  setdownTopic: cloud/gcid/setdown

spring:
    #redis配置
  redis:
    host: 10.71.16.208
    port: 16379
    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.71.16.96:3306/zz_originaldata?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: pbsage
    password: 123456


server:
  port: 8111
#广场ID及GatewayId
epc:
  gatewayId: BYQ
  gcId: 3506811020
  tableId: 3506810001
  subsystem: byq/
  threadNum: 1

beanName: electricEpcDevice

